import Form from "@/components/Form";
import Header from "@/components/Header";
import Posts from "@/components/posts/Posts";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Clone | Alxsdlr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header label={"Home"} />
      <Form placeholder="What's happening?" />
      <Posts />
    </>
  );
}
