import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter Clone | Alxsdlr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-center text-indigo-500'>Hello World</div>
    </>
  )
}
